<?php

namespace App\Error;

use Exception;
use Cake\Error\BaseErrorHandler;

class AppError extends BaseErrorHandler {

    public function _displayError($error, $debug) {
        return 'There has been an error!';
    }

    public function _displayException($exception) {
        die('d_exception');
    }

    public function handleException(Exception $exception)
    {
        die('H_exception');
        parent::handleException($exception); // TODO: Change the autogenerated stub
    }


}